server:
  port: 8000 

spring:
  application:
    name: landback
  security:
    user:
      password: 
  
  mail:
    host: smtp.naver.com
    port: 587
    username: qwer4667@naver.com
    password: hh890807^^
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://96junghos.mooo.com:12503/landback?serverTimezone=Asia/Seoul
    username: tj705
    password: tj705
